'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tarefa
    Public Property Tarid As Integer
    Public Property tarDescricao As String
    Public Property tardedata As Nullable(Of Date)
    Public Property tarfeito As Boolean
    Public Property PESID As Integer

    Public Overridable Property Pessoa As Pessoa

End Class
